### ISSUE TITLE
Deleted topics, events still shown

### ISSUE THREAD

**Issue by frissdiegurke** [pitaj/nodebb-plugin-calendar#38]
Similar to #34, if you delete a topic, events of covered posts should not show up within the calendar anymore.

**Comment by pitaj** [comment]
They may show up only if you have permissions to view deleted topics (and therefore the posts within). Since I'd like to keep as close to the core permissions as possible as far as event access goes, at the moment I'm going to label this as wontfix and request arguments for changing the current behavior.

**Comment by frissdiegurke** [comment]
Maybe you could indicate deleted ones by changing the opacity within the calendar view? At least it should be indicated in some way thought.
