### ISSUE TITLE
Guests can access and vote in the RSVP system

### ISSUE THREAD

**Issue by gnucoder** [pitaj/nodebb-plugin-calendar#59]
We authorize guests to access our forum in read only mode, so they can access the calendar et see the events, but they should not access to the rsvp... In the current version (V0.8 Alpha) ghests do have access and can use the rsvp, so after voting, we have some ghost user listed as attending...

**Comment by pitaj** [comment]
How do you propose this be fixed? There are two options that I can see:

1. Add setting to link the response permission to the reply permission instead of the view permission
2. Add an extra permission field for responding to events

I'd rather do option 1 than option 2, just because I prefer staying as close to native permissions as possible.

**Comment by gnucoder** [comment]
Close to native works for me ^^

**Comment by pitaj** [comment]
Actually, thinking more about this, I will add this setting anyways, but I think I will also prevent guests from responding in general since it just doesn't make sense.

**Comment by gnucoder** [comment]
True :)
