### ISSUE TITLE
Display a map + link to Google Maps for event location

### ISSUE THREAD

**Issue by gnucoder** [pitaj/nodebb-plugin-calendar#60]
It will be nice to have a map preview of the address of the event. On click, it could open it in Google Maps.

**Comment by pitaj** [comment]
Hmm. This sounds interesting, but a little out of the scope of the plugin.

There is a solution that I think will fill your use case. Since the location field for an event is pasred as a post, you could use the _nodebb-plugin-embed-gmap_ plugin and `[map location]` in the location field of the calendar.

**Comment by gnucoder** [comment]
Tks for gmap plugin :)
